name: Build and Deploy

# 触发 workflow 的事件
on:
  push:
    branches:
      - main

# 一个workflow由执行的一项或多项job
jobs:
  # 一个job任务，任务名为build
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18 ]
    # 步骤合集
    steps:
      - name: Checkout code
        #使用checkout@v2这个action获取源码
        uses: actions/checkout@v3
      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Setup node
        uses: actions/setup-node@v3
        #指定某个action 可能需要输入的参数
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodeModules-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodeModules-
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: pnpm install
      - name: Build project
        run: pnpm build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./dist
